#include<iostream>
using namespace std;
int main()
{
  /**/cout << " ---------------------------------------------------------------------------------" << endl;
    cout << "                         #       #####   ######   #####  ######                   " << endl;
    cout << "                        #       #       #        #      #    #                    " << endl;
    cout << "                       #       ####    ######   #      #    #                     " << endl;
    cout << "                      #       #            #   #      #    #                      " << endl;
    cout << "                     ######  #####   ######   #####  ######                       " << endl;
    cout << " ---------------------------------------------------------------------------------" << endl;
    cout << "\t\t==================================================\n";
    cout << "\t\t\t  LAHORE ELECTRIC SUPPLY COMPANY  \n";
    cout << "\t\t==================================================\n\n";
    cout << "\t\t\t----------------------------------\n";
    cout << "\t\t\t||\t  EMPLOYEE PORTAL   \t||\n";
    cout << "\t\t\t||\t    1.Register      \t||\n";
    cout << "\t\t\t||\t    2.Login         \t||\n";
    cout << "\t\t\t||\t    3.Exit          \t||\n";
    cout << "\t\t\t----------------------------------\n";
    cout << endl << " ------------------------------REGISTERATION PORTAL------------------------------" << endl << endl;
	cout << endl << " ----------------------------------LOGIN PORTAL----------------------------------" << endl << endl;
	cout << endl << " --------------------------------EMPLOYEE PORTAL---------------------------------" << endl << endl;
    cout << "\t\t\t----------------------------------\n";
    cout << "\t\t\t||   1.ADD A CUSTOMER     \t||\n";
	cout << "\t\t\t||   2.DISPLAY            \t||\n";
	cout << "\t\t\t||   3.SEARCH             \t||\n";
	cout << "\t\t\t||   4.UPDATE CNIC EXPIRY DATE\t||\n";
	cout << "\t\t\t||   5.BILLING INFO       \t||\n";
	cout << "\t\t\t||   6.UPDATE A TARIFF    \t||\n";
    cout << "\t\t\t----------------------------------\n";
	cout << endl << " -----------------------ENTER DETAILS FOR A NEW CUSTOMER-------------------------" << endl << endl;
	cout << endl << " -------------------------ENTER DETAILS FOR A NEW BILL---------------------------" << endl << endl;
	cout << endl << " -----------------------------------BILLING--------------------------------------" << endl << endl;
    cout << "\t\t\t------------------------------------------\n";
	cout << "\t\t\t||\t1.ADD NEW BILL INFO\t\t||\n";
	cout << "\t\t\t||\t2.DISPLAY BILL INFO\t\t||\n";
	cout << "\t\t\t||\t3.VIEW A BILL      \t\t||\n";
	cout << "\t\t\t||\t4.PAY BILL         \t\t||\n";
	cout << "\t\t\t||\t5.VIEW PAID AND UNPAID BILLS\t||\n";
	cout << "\t\t\t------------------------------------------\n";
	cout << endl << " -------------------------------UPDATING TARIFF----------------------------------" << endl << endl;
    cout << "\t\t\t----------------------------------\n";
	cout << "\t\t\t||    1.UPDATE INFO        \t||\n";
	cout << "\t\t\t||    2.DISPLAY INFO       \t||\n";
	cout << "\t\t\t||    3.DISPLAY TARIFF FILE\t||\n";
	cout << "\t\t\t----------------------------------\n";
    cout << "\t\t==================================================\n";
    cout << "\t\t\t\t  ELECTRICITY BILL\n";
    cout << "\t\t==================================================\n\n";
    cout << "\t\t--------------------------------------------------\n";
    cout << "\t\t||\t CUSTOMER ID  \t:" << "code"     << "\t\t\t||\n";
    cout << "\t\t||\t NAME         \t:" << "name"     << "\t\t\t||\n";
    cout << "\t\t||\t ADDRESS      \t:" << "address"  << "\t\t||\n";
    cout << "\t\t||\t PHONE NUMBER \t:" << "phone"    << "\t\t\t||\n";
    cout << "\t\t||\t CUSTOMER TYPE\t:" << "ct"       << "\t\t\t||\n";
    cout << "\t\t||\t METER TYPE   \t:" << "mt"       << "\t\t\t||\n";
    cout << "\t\t||\t TARIFF       \t:" << "tariff"   << "\t\t\t||\n";
    cout << "\t\t||\t-------------------------\t\t||\n";
    cout << "\t\t||\t TOTAL BILL   \t:" << "may"      << "    \t\t||\n";
    cout << "\t\t||\t TOTAL BILL   \t:" << "september"<< "    \t\t||\n";
    cout << "\t\t||\t TOTAL UNIT   \t:" << "unit"     << "\t\t\t||\n";
    cout << "\t\t||\t DUE DATE     \t:" << "dd/mm/yyyy"<<"\t\t||\n";
    cout << "\t\t||\t STATUS       \t:" << "status"   << "\t\t\t||\n";
    cout << "\t\t--------------------------------------------------\n";
    cout << "\t\t--------------------------------------------------\n";
}
